'caverns_and_chasms:copper_grate',
'caverns_and_chasms:exposed_copper_grate',
'caverns_and_chasms:oxidized_copper_grate',
'caverns_and_chasms:waxed_copper_grate',
'caverns_and_chasms:waxed_exposed_copper_grate',
'caverns_and_chasms:waxed_oxidized_copper_grate',
'caverns_and_chasms:waxed_weathered_copper_grate',
'caverns_and_chasms:weathered_copper_grate',

'caverns_and_chasms:copper_door',
'caverns_and_chasms:exposed_copper_door',
'caverns_and_chasms:oxidized_copper_door',
'caverns_and_chasms:waxed_copper_door',
'caverns_and_chasms:waxed_exposed_copper_door',
'caverns_and_chasms:waxed_oxidized_copper_door',
'caverns_and_chasms:waxed_weathered_copper_door',
'caverns_and_chasms:weathered_copper_door',

'caverns_and_chasms:copper_bulb',
'caverns_and_chasms:exposed_copper_bulb',
'caverns_and_chasms:oxidized_copper_bulb',
'caverns_and_chasms:waxed_copper_bulb',
'caverns_and_chasms:waxed_exposed_copper_bulb',
'caverns_and_chasms:waxed_oxidized_copper_bulb',
'caverns_and_chasms:waxed_weathered_copper_bulb',
'caverns_and_chasms:weathered_copper_bulb',

'caverns_and_chasms:weathered_copper_trapdoor',
'caverns_and_chasms:copper_trapdoor',
'caverns_and_chasms:exposed_copper_trapdoor',
'caverns_and_chasms:oxidized_copper_trapdoor',
'caverns_and_chasms:waxed_copper_trapdoor',
'caverns_and_chasms:waxed_exposed_copper_trapdoor',
'caverns_and_chasms:waxed_oxidized_copper_trapdoor',
'caverns_and_chasms:waxed_weathered_copper_trapdoor',