//priority: 0
ItemEvents.modification(event => {
	//Experimental:
	function stackTo256(x) {
		event.modify(x, item => {item.maxStackSize = 256})
	}

	function stackTo64(x) {
		event.modify(x, item => {item.maxStackSize = 64})
	}
	function stackTo16(x) {
		event.modify(x, item => {item.maxStackSize = 16})
	}
	function stackTo8(x) {
		event.modify(x, item => {item.maxStackSize = 8})
	}
	function stackTo1(x) {
		event.modify(x, item => {item.maxStackSize = 1})
	}

//Bottles:
	stackTo1('alexsmobs:fish_oil')
	stackTo1('alexsmobs:stink_bottle')
	stackTo1('farmersdelight:milk_bottle')
	stackTo1('minecraft:dragon_breath')
	stackTo1('minecraft:honey_bottle')
	stackTo1('quark:bottled_cloud')
	stackTo1('snowyspirit:eggnog')
	stackTo1('supplementaries:antique_ink')
	stackTo1('upgrade_aquatic:mulberry_jam_bottle')

//Other Ones:
	stackTo1('minecraft:cake')
	stackTo1('minecraft:mushroom_stew')
	stackTo1('minecraft:pumpkin_pie')
	stackTo1('minecraft:suspicious_stew')
	stackTo1('quark:tiny_potato')
	stackTo1('upgrade_aquatic:mulberry_pie')
	stackTo1('minecraft:compass')
	stackTo1('minecraft:recovery_compass')
	stackTo1('supplementaries:altimeter')
	stackTo1('galosphere:barometer')
	stackTo1('minecraft:clock')

//Golden Food:
	stackTo1('etcetera:golden_eggple')
	stackTo1('galosphere:golden_lichen_cordyceps')
	stackTo1('kubejs:golden_potato')
	stackTo1('minecraft:enchanted_golden_apple')
	stackTo1('minecraft:glistering_melon_slice')
	stackTo1('minecraft:golden_apple')
	stackTo1('minecraft:golden_carrot')

//Boss Stuff:
	stackTo1('minecraft:dragon_egg')
	stackTo1('minecraft:heart_of_the_sea')
	stackTo1('minecraft:nether_star')
	stackTo1('rediscovered:red_dragon_egg')
	stackTo1('upgrade_aquatic:elder_eye')

//Other:
	stackTo8('alexsmobs:banana')
	stackTo8('alexsmobs:cooked_catfish')
	stackTo8('alexsmobs:cosmic_cod')
	stackTo8('alexsmobs:flying_fish')
	stackTo8('alexsmobs:raw_catfish')
	stackTo8('culturaldelights:rice_ball')
	stackTo8('culturaldelights:tortilla')
	stackTo8('ecologics:coconut_slice')
	stackTo8('ecologics:cooked_prickly_pear')
	stackTo8('ecologics:prickly_pear')
	stackTo8('ecologics:walnut')
	stackTo8('etcetera:eggple')

	stackTo8('farmersdelight:fried_egg')
	stackTo8('farmersdelight:honey_cookie')
	stackTo8('farmersdelight:pumpkin_slice')
	stackTo8('farmersdelight:rice')
	stackTo8('farmersdelight:sweet_berry_cookie')
	stackTo8('galosphere:lichen_cordyceps')
	stackTo8('habitat:kabloom_pulp')
	stackTo8('hauntedharvest:corn')
	stackTo8('hauntedharvest:grim_apple')
	stackTo8('hauntedharvest:rotten_apple')

	stackTo8('kubejs:omelette')
	stackTo8('kubejs:waffle')
	stackTo8('minecraft:apple')
	stackTo8('minecraft:baked_potato')
	stackTo8('minecraft:beef')
	stackTo8('minecraft:beetroot')
	stackTo8('minecraft:bread')
	stackTo8('minecraft:carrot')
	stackTo8('minecraft:chicken')
	stackTo8('minecraft:chorus_fruit')
	stackTo8('minecraft:cod')
	stackTo8('minecraft:cooked_beef')
	stackTo8('minecraft:cooked_chicken')
	stackTo8('minecraft:cooked_cod')
	stackTo8('minecraft:cooked_mutton')
	stackTo8('minecraft:cooked_porkchop')
	stackTo8('minecraft:cooked_rabbit')
	stackTo8('minecraft:cooked_salmon')
	stackTo8('minecraft:glow_berries')
	stackTo8('minecraft:melon')
	stackTo8('minecraft:melon_slice')
	stackTo8('minecraft:mutton')
	stackTo8('minecraft:poisonous_potato')
	stackTo8('minecraft:popped_chorus_fruit')
	stackTo8('minecraft:porkchop')
	stackTo8('minecraft:potato')
	stackTo8('minecraft:pufferfish')
	stackTo8('minecraft:rabbit')
	stackTo8('minecraft:rabbit_foot')
	stackTo8('minecraft:rotten_flesh')
	stackTo8('minecraft:salmon')
	stackTo8('minecraft:sweet_berries')
	stackTo8('minecraft:tropical_fish')
	stackTo8('quark:ancient_fruit')
	stackTo8('rediscovered:cooked_fish')
	stackTo8('rediscovered:raw_fish')
	stackTo8('upgrade_aquatic:cooked_pike')
	stackTo8('upgrade_aquatic:mulberry')
	stackTo8('upgrade_aquatic:pike')

	stackTo16('farmersdelight:honey_cookie')
	stackTo16('farmersdelight:rice_panicle')
	stackTo16('farmersdelight:sweet_berry_cookie')
	stackTo16('kubejs:butter')
	stackTo16('kubejs:marshmallow')
	stackTo16('minecraft:cocoa_beans')
	stackTo16('minecraft:cookie')
	stackTo16('minecraft:dried_kelp')
	stackTo16('minecraft:honeycomb')
	stackTo16('minecraft:kelp')
	stackTo16('minecraft:nether_wart')
	stackTo16('minecraft:sugar')
	stackTo16('minecraft:sugar_cane')
	stackTo16('minecraft:wheat')
	stackTo16('spelunkery:salt')
	stackTo16('supplementaries:candy')
	stackTo16('supplementaries:pancake')
	stackTo16('supplementaries:soap')

//Eggs:
	stackTo16('alexsmobs:caiman_egg')
	stackTo16('alexsmobs:crocodile_egg')
	stackTo16('alexsmobs:platypus_egg')
	stackTo16('alexsmobs:terrapin_egg')
	stackTo16('friendsandfoes:crab_egg')
	stackTo16('minecraft:sniffer_egg')
	stackTo16('minecraft:turtle_egg')
	stackTo16('savage_and_ravage:creeper_spores')

//Seeds:
	stackTo16('minecraft:beetroot_seeds')
	stackTo16('minecraft:melon_seeds')
	stackTo16('minecraft:pumpkin_seeds')
	stackTo16('minecraft:torchflower_seeds')
	stackTo16('minecraft:wheat_seeds')
	stackTo16('minecraft:pitcher_pod')

//Mushrooms:
	stackTo16('galosphere:bowl_lichen')
	stackTo16('minecraft:brown_mushroom')
	stackTo16('minecraft:crimson_fungus')
	stackTo16('minecraft:red_mushroom')
	stackTo16('minecraft:warped_fungus')
	stackTo16('quark:glow_shroom')
	stackTo16('spelunkery:button_mushroom')
	stackTo16('spelunkery:crimini')
	stackTo16('spelunkery:grilled_portabella')
	stackTo16('spelunkery:inkcap_mushroom')
	stackTo16('spelunkery:milly_bubcap')
	stackTo16('spelunkery:mushgloom')
	stackTo16('spelunkery:phosphor_fungus')
	stackTo16('spelunkery:portabella')
	stackTo16('spelunkery:white_inkcap_mushroom')

//Other:
	stackTo256('minecraft:ender_pearl')
	stackTo256('minecraft:snowball')
	stackTo256('spelunkery:dust_bun')
	stackTo256('galosphere:silver_bomb')
	
	stackTo1('minecraft:experience_bottle')
	stackTo1('spelunkery:portal_fluid_bottle')
	stackTo1('alexsmobs:ambergris')
})

stackTo256('alexsmobs:banner_pattern_australia_0')
stackTo256('alexsmobs:banner_pattern_australia_1')
stackTo256('alexsmobs:banner_pattern_bear')
stackTo256('alexsmobs:banner_pattern_brazil')
stackTo256('alexsmobs:banner_pattern_new_mexico')
stackTo256('alexsmobs:bear_dust')
stackTo256('alexsmobs:bear_fur')
stackTo256('alexsmobs:bison_fur')
stackTo256('alexsmobs:caiman_egg')
stackTo256('alexsmobs:chorus_on_a_stick')
stackTo256('alexsmobs:crocodile_chestplate')
stackTo256('alexsmobs:crocodile_egg')
stackTo256('alexsmobs:dimensional_carver')
stackTo256('alexsmobs:dropbear_claw')
stackTo256('alexsmobs:emu_egg')
stackTo256('alexsmobs:farseer_arm')
stackTo256('alexsmobs:fedora')
stackTo256('alexsmobs:flying_fish_boots')
stackTo256('alexsmobs:froststalker_horn')
stackTo256('alexsmobs:ghostly_pickaxe')
stackTo256('alexsmobs:maraca')
stackTo256('alexsmobs:moose_antler')
stackTo256('alexsmobs:mungal_spores')
stackTo256('alexsmobs:music_disc_thime')
stackTo256('alexsmobs:novelty_hat')
stackTo256('alexsmobs:platypus_egg')
stackTo256('alexsmobs:sculk_boomer')
stackTo256('alexsmobs:shattered_dimensional_carver')
stackTo256('alexsmobs:sombrero')
stackTo256('alexsmobs:soul_heart')
stackTo256('alexsmobs:spawn_egg_anteater' )
stackTo256('alexsmobs:spawn_egg_bald_eagle' )
stackTo256('alexsmobs:spawn_egg_bison' )
stackTo256('alexsmobs:spawn_egg_blue_jay' )
stackTo256('alexsmobs:spawn_egg_bunfungus' )
stackTo256('alexsmobs:spawn_egg_caiman' )
stackTo256('alexsmobs:spawn_egg_catfish' )
stackTo256('alexsmobs:spawn_egg_crocodile' )
stackTo256('alexsmobs:spawn_egg_crow' )
stackTo256('alexsmobs:spawn_egg_devils_hole_pupfish' )
stackTo256('alexsmobs:spawn_egg_dropbear' )
stackTo256('alexsmobs:spawn_egg_emu' )
stackTo256('alexsmobs:spawn_egg_endergrade' )
stackTo256('alexsmobs:spawn_egg_farseer' )
stackTo256('alexsmobs:spawn_egg_flutter' )
stackTo256('alexsmobs:spawn_egg_flying_fish' )
stackTo256('alexsmobs:spawn_egg_froststalker' )
stackTo256('alexsmobs:spawn_egg_gelada_monkey' )
stackTo256('alexsmobs:spawn_egg_gorilla' )
stackTo256('alexsmobs:spawn_egg_grizzly_bear' )
stackTo256('alexsmobs:spawn_egg_hummingbird' )
stackTo256('alexsmobs:spawn_egg_jerboa' )
stackTo256('alexsmobs:spawn_egg_komodo_dragon' )
stackTo256('alexsmobs:spawn_egg_laviathan' )
stackTo256('alexsmobs:spawn_egg_maned_wolf' )
stackTo256('alexsmobs:spawn_egg_moose' )
stackTo256('alexsmobs:spawn_egg_mudskipper' )
stackTo256('alexsmobs:spawn_egg_mungus' )
stackTo256('alexsmobs:spawn_egg_orca' )
stackTo256('alexsmobs:spawn_egg_platypus' )
stackTo256('alexsmobs:spawn_egg_potoo' )
stackTo256('alexsmobs:spawn_egg_raccoon' )
stackTo256('alexsmobs:spawn_egg_rain_frog' )
stackTo256('alexsmobs:spawn_egg_roadrunner' )
stackTo256('alexsmobs:spawn_egg_seagull' )
stackTo256('alexsmobs:spawn_egg_seal' )
stackTo256('alexsmobs:spawn_egg_shoebill' )
stackTo256('alexsmobs:spawn_egg_skreecher' )
stackTo256('alexsmobs:spawn_egg_snow_leopard' )
stackTo256('alexsmobs:spawn_egg_straddler' )
stackTo256('alexsmobs:spawn_egg_stradpole' )
stackTo256('alexsmobs:spawn_egg_sugar_glider' )
stackTo256('alexsmobs:spawn_egg_sunbird' )
stackTo256('alexsmobs:spawn_egg_tasmanian_devil' )
stackTo256('alexsmobs:spawn_egg_terrapin' )
stackTo256('alexsmobs:spawn_egg_tiger' )
stackTo256('alexsmobs:spawn_egg_toucan' )
stackTo256('alexsmobs:spawn_egg_triops' )
stackTo256('alexsmobs:spawn_egg_tusklin' )
stackTo256('alexsmobs:spawn_egg_underminer' )
stackTo256('alexsmobs:straddle_helmet')
stackTo256('alexsmobs:straddle_saddle')
stackTo256('alexsmobs:straddleboard')
stackTo256('alexsmobs:straddlite')
stackTo256('alexsmobs:terrapin_egg')
stackTo256('alexsmobs:triops_eggs')
stackTo256('alexsmobs:unsettling_kimono')
stackTo256('chalk:black_chalk')
stackTo256('chalk:blue_chalk')
stackTo256('chalk:brown_chalk')
stackTo256('chalk:cyan_chalk')
stackTo256('chalk:gray_chalk')
stackTo256('chalk:green_chalk')
stackTo256('chalk:light_blue_chalk')
stackTo256('chalk:light_gray_chalk')
stackTo256('chalk:lime_chalk')
stackTo256('chalk:magenta_chalk')
stackTo256('chalk:orange_chalk')
stackTo256('chalk:pink_chalk')
stackTo256('chalk:purple_chalk')
stackTo256('chalk:red_chalk')
stackTo256('chalk:white_chalk')
stackTo256('chalk:yellow_chalk')
stackTo256('clayworks:black_decorated_pot')
stackTo256('clayworks:black_terracotta_slab')
stackTo256('clayworks:black_terracotta_stairs')
stackTo256('clayworks:black_terracotta_wall')
stackTo256('clayworks:blue_decorated_pot')
stackTo256('clayworks:blue_terracotta_slab')
stackTo256('clayworks:blue_terracotta_stairs')
stackTo256('clayworks:blue_terracotta_wall')
stackTo256('clayworks:brown_decorated_pot')
stackTo256('clayworks:brown_terracotta_slab')
stackTo256('clayworks:brown_terracotta_stairs')
stackTo256('clayworks:brown_terracotta_wall')
stackTo256('clayworks:chiseled_bricks')
stackTo256('clayworks:cyan_decorated_pot')
stackTo256('clayworks:cyan_terracotta_slab')
stackTo256('clayworks:cyan_terracotta_stairs')
stackTo256('clayworks:cyan_terracotta_wall')
stackTo256('clayworks:gray_decorated_pot')
stackTo256('clayworks:gray_terracotta_slab')
stackTo256('clayworks:gray_terracotta_stairs')
stackTo256('clayworks:gray_terracotta_wall')
stackTo256('clayworks:green_decorated_pot')
stackTo256('clayworks:green_terracotta_slab')
stackTo256('clayworks:green_terracotta_stairs')
stackTo256('clayworks:green_terracotta_wall')
stackTo256('clayworks:light_blue_decorated_pot')
stackTo256('clayworks:light_blue_terracotta_slab')
stackTo256('clayworks:light_blue_terracotta_stairs')
stackTo256('clayworks:light_blue_terracotta_wall')
stackTo256('clayworks:light_gray_decorated_pot')
stackTo256('clayworks:light_gray_terracotta_slab')
stackTo256('clayworks:light_gray_terracotta_stairs')
stackTo256('clayworks:light_gray_terracotta_wall')
stackTo256('clayworks:lime_decorated_pot')
stackTo256('clayworks:lime_terracotta_slab')
stackTo256('clayworks:lime_terracotta_stairs')
stackTo256('clayworks:lime_terracotta_wall')
stackTo256('clayworks:magenta_decorated_pot')
stackTo256('clayworks:magenta_terracotta_slab')
stackTo256('clayworks:magenta_terracotta_stairs')
stackTo256('clayworks:magenta_terracotta_wall')
stackTo256('clayworks:orange_decorated_pot')
stackTo256('clayworks:orange_terracotta_slab')
stackTo256('clayworks:orange_terracotta_stairs')
stackTo256('clayworks:orange_terracotta_wall')
stackTo256('clayworks:pink_decorated_pot')
stackTo256('clayworks:pink_terracotta_slab')
stackTo256('clayworks:pink_terracotta_stairs')
stackTo256('clayworks:pink_terracotta_wall')
stackTo256('clayworks:purple_decorated_pot')
stackTo256('clayworks:purple_terracotta_slab')
stackTo256('clayworks:purple_terracotta_stairs')
stackTo256('clayworks:purple_terracotta_wall')
stackTo256('clayworks:red_decorated_pot')
stackTo256('clayworks:red_terracotta_slab')
stackTo256('clayworks:red_terracotta_stairs')
stackTo256('clayworks:red_terracotta_wall')
stackTo256('clayworks:terracotta_slab')
stackTo256('clayworks:terracotta_stairs')
stackTo256('clayworks:terracotta_wall')
stackTo256('clayworks:white_decorated_pot')
stackTo256('clayworks:white_terracotta_slab')
stackTo256('clayworks:white_terracotta_stairs')
stackTo256('clayworks:white_terracotta_wall')
stackTo256('clayworks:yellow_decorated_pot')
stackTo256('clayworks:yellow_terracotta_slab')
stackTo256('clayworks:yellow_terracotta_stairs')
stackTo256('clayworks:yellow_terracotta_wall')
stackTo256('copperandtuffbackport:copper_bulb')
stackTo256('copperandtuffbackport:copper_door')
stackTo256('copperandtuffbackport:copper_grate')
stackTo256('copperandtuffbackport:copper_trapdoor')
stackTo256('copperandtuffbackport:tuff_slab')
stackTo256('copperandtuffbackport:tuff_stairs')
stackTo256('copperandtuffbackport:tuff_wall')
stackTo256('easel_does_it:easel')
stackTo256('ecologics:thin_ice')
stackTo256('etcetera:bismuth_ingot')
stackTo256('etcetera:black_hat')
stackTo256('etcetera:black_sweater')
stackTo256('etcetera:blue_hat')
stackTo256('etcetera:blue_sweater')
stackTo256('etcetera:bouquet')
stackTo256('etcetera:brown_hat')
stackTo256('etcetera:brown_sweater')
stackTo256('etcetera:chapple_spawn_egg' )
stackTo256('etcetera:cotton_flower')
stackTo256('etcetera:cyan_hat')
stackTo256('etcetera:cyan_sweater')
stackTo256('etcetera:dice')
stackTo256('etcetera:drum')
stackTo256('etcetera:gray_hat')
stackTo256('etcetera:gray_sweater')
stackTo256('etcetera:green_hat')
stackTo256('etcetera:green_sweater')
stackTo256('etcetera:handbell')
stackTo256('etcetera:iridescent_terracotta')
stackTo256('etcetera:iridescent_wool')
stackTo256('etcetera:light_blue_hat')
stackTo256('etcetera:light_blue_sweater')
stackTo256('etcetera:light_gray_hat')
stackTo256('etcetera:light_gray_sweater')
stackTo256('etcetera:lime_hat')
stackTo256('etcetera:lime_sweater')
stackTo256('etcetera:magenta_hat')
stackTo256('etcetera:magenta_sweater')
stackTo256('etcetera:nether_bismuth_ore')
stackTo256('etcetera:orange_hat')
stackTo256('etcetera:orange_sweater')
stackTo256('etcetera:pink_hat')
stackTo256('etcetera:pink_sweater')
stackTo256('etcetera:prickly_can')
stackTo256('etcetera:purple_hat')
stackTo256('etcetera:purple_sweater')
stackTo256('etcetera:raw_bismuth')
stackTo256('etcetera:red_hat')
stackTo256('etcetera:red_sweater')
stackTo256('etcetera:terracotta_vase')
stackTo256('etcetera:tidal_helmet')
stackTo256('etcetera:trader_hood')
stackTo256('etcetera:trader_robe')
stackTo256('etcetera:turtle_raft')
stackTo256('etcetera:white_hat')
stackTo256('etcetera:white_sweater')
stackTo256('etcetera:yellow_hat')
stackTo256('etcetera:yellow_sweater')
stackTo256('etched:jukebox_minecart')
stackTo256('farmersdelight:basket')
stackTo256('farmersdelight:canvas_sign')
stackTo256('farmersdelight:hanging_canvas_sign')
stackTo256('farmersdelight:organic_compost')
stackTo256('farmersdelight:rich_soil')
stackTo256('farmersdelight:rich_soil_farmland')
stackTo256('friendsandfoes:copper_button')
stackTo256('friendsandfoes:copper_golem_spawn_egg' )
stackTo256('friendsandfoes:crab_egg')
stackTo256('friendsandfoes:crab_spawn_egg' )
stackTo256('friendsandfoes:glare_spawn_egg' )
stackTo256('friendsandfoes:moobloom_spawn_egg' )
stackTo256('friendsandfoes:tuff_golem_spawn_egg' )
stackTo256('galosphere:barometer')
stackTo256('galosphere:bowl_lichen')
stackTo256('galosphere:cured_membrane')
stackTo256('galosphere:lichen_moss')
stackTo256('galosphere:lichen_roots')
stackTo256('galosphere:lichen_shelf')
stackTo256('galosphere:raw_silver')
stackTo256('galosphere:raw_silver_block')
stackTo256('galosphere:silver_bomb')
stackTo256('galosphere:silver_ingot')
stackTo256('galosphere:silver_lattice')
stackTo256('galosphere:silver_nugget')
stackTo256('galosphere:silver_ore')
stackTo256('galosphere:spectre_flare')
stackTo256('galosphere:spectre_spawn_egg' )
stackTo256('habitat:blowball')
stackTo256('habitat:edelweiss')
stackTo256('habitat:passerine_spawn_egg' )
stackTo256('hardcore_torches:burnt_torch')
stackTo256('hardcore_torches:lit_torch')
stackTo256('hauntedharvest:paper_bag')
stackTo256('kubejs:ancient_rod')
stackTo256('kubejs:bismuth_pickaxe')
stackTo256('kubejs:chiseled_gloomy_tiles')
stackTo256('kubejs:cobalt')
stackTo256('kubejs:copper_axe')
stackTo256('kubejs:copper_hoe')
stackTo256('kubejs:copper_pickaxe')
stackTo256('kubejs:copper_shovel')
stackTo256('kubejs:copper_sword')
stackTo256('kubejs:gloomy_tiles')
stackTo256('kubejs:gloomy_tiles_slab')
stackTo256('kubejs:gloomy_tiles_stairs')
stackTo256('kubejs:gloomy_tiles_wall')
stackTo256('kubejs:glow_paste')
stackTo256('kubejs:halite_crystal')
stackTo256('kubejs:lava_lamp')
stackTo256('kubejs:music_disc_dog')
stackTo256('kubejs:music_disc_droopy2')
stackTo256('kubejs:music_disc_eleven')
stackTo256('kubejs:mysterious_stone')
stackTo256('kubejs:rock_salt')
stackTo256('kubejs:sharp_tooth')
stackTo256('kubejs:soul_dust')
stackTo256('mace_backport:mace')
stackTo256('minecraft:acacia_button')
stackTo256('minecraft:acacia_door')
stackTo256('minecraft:acacia_fence')
stackTo256('minecraft:acacia_fence_gate')
stackTo256('minecraft:acacia_hanging_sign')
stackTo256('minecraft:acacia_leaves')
stackTo256('minecraft:acacia_log')
stackTo256('minecraft:acacia_planks')
stackTo256('minecraft:acacia_pressure_plate')
stackTo256('minecraft:acacia_sapling')
stackTo256('minecraft:acacia_sign')
stackTo256('minecraft:acacia_slab')
stackTo256('minecraft:acacia_stairs')
stackTo256('minecraft:acacia_trapdoor')
stackTo256('minecraft:acacia_wood')
stackTo256('minecraft:activator_rail')
stackTo256('minecraft:allay_spawn_egg' )
stackTo256('minecraft:allium')
stackTo256('minecraft:amethyst_block')
stackTo256('minecraft:amethyst_cluster')
stackTo256('minecraft:amethyst_shard')
stackTo256('minecraft:ancient_debris')
stackTo256('minecraft:andesite')
stackTo256('minecraft:andesite_slab')
stackTo256('minecraft:andesite_stairs')
stackTo256('minecraft:andesite_wall')
stackTo256('minecraft:armor_stand')
stackTo256('minecraft:arrow')
stackTo256('minecraft:axolotl_spawn_egg' )
stackTo256('minecraft:azure_bluet')
stackTo256('minecraft:bamboo')
stackTo256('minecraft:bamboo_block')
stackTo256('minecraft:bamboo_button')
stackTo256('minecraft:bamboo_door')
stackTo256('minecraft:bamboo_fence')
stackTo256('minecraft:bamboo_fence_gate')
stackTo256('minecraft:bamboo_hanging_sign')
stackTo256('minecraft:bamboo_mosaic')
stackTo256('minecraft:bamboo_mosaic_slab')
stackTo256('minecraft:bamboo_mosaic_stairs')
stackTo256('minecraft:bamboo_planks')
stackTo256('minecraft:bamboo_pressure_plate')
stackTo256('minecraft:bamboo_raft')
stackTo256('minecraft:bamboo_sign')
stackTo256('minecraft:bamboo_slab')
stackTo256('minecraft:bamboo_stairs')
stackTo256('minecraft:bamboo_trapdoor')
stackTo256('minecraft:barrel')
stackTo256('minecraft:basalt')
stackTo256('minecraft:bat_spawn_egg' )
stackTo256('minecraft:beacon')
stackTo256('minecraft:bedrock')
stackTo256('minecraft:bee_nest')
stackTo256('minecraft:bee_spawn_egg' )
stackTo256('minecraft:beehive')
stackTo256('minecraft:beetroot_seeds')
stackTo256('minecraft:bell')
stackTo256('minecraft:big_dripleaf')
stackTo256('minecraft:birch_button')
stackTo256('minecraft:birch_door')
stackTo256('minecraft:birch_fence')
stackTo256('minecraft:birch_fence_gate')
stackTo256('minecraft:birch_hanging_sign')
stackTo256('minecraft:birch_leaves')
stackTo256('minecraft:birch_log')
stackTo256('minecraft:birch_planks')
stackTo256('minecraft:birch_pressure_plate')
stackTo256('minecraft:birch_sapling')
stackTo256('minecraft:birch_sign')
stackTo256('minecraft:birch_slab')
stackTo256('minecraft:birch_stairs')
stackTo256('minecraft:birch_trapdoor')
stackTo256('minecraft:birch_wood')
stackTo256('minecraft:black_bed')
stackTo256('minecraft:black_candle')
stackTo256('minecraft:black_carpet')
stackTo256('minecraft:black_dye')
stackTo256('minecraft:black_stained_glass')
stackTo256('minecraft:black_stained_glass_pane')
stackTo256('minecraft:black_terracotta')
stackTo256('minecraft:black_wool')
stackTo256('minecraft:blackstone')
stackTo256('minecraft:blackstone_slab')
stackTo256('minecraft:blackstone_stairs')
stackTo256('minecraft:blackstone_wall')
stackTo256('minecraft:blaze_powder')
stackTo256('minecraft:blaze_rod')
stackTo256('minecraft:blaze_spawn_egg' )
stackTo256('minecraft:blue_bed')
stackTo256('minecraft:blue_candle')
stackTo256('minecraft:blue_carpet')
stackTo256('minecraft:blue_dye')
stackTo256('minecraft:blue_ice')
stackTo256('minecraft:blue_orchid')
stackTo256('minecraft:blue_stained_glass')
stackTo256('minecraft:blue_stained_glass_pane')
stackTo256('minecraft:blue_terracotta')
stackTo256('minecraft:blue_wool')
stackTo256('minecraft:bone')
stackTo256('minecraft:bone_block')
stackTo256('minecraft:bone_meal')
stackTo256('minecraft:book')
stackTo256('minecraft:bookshelf')
stackTo256('minecraft:bow')
stackTo256('minecraft:brain_coral_block')
stackTo256('minecraft:brewing_stand')
stackTo256('minecraft:brick')
stackTo256('minecraft:brick_slab')
stackTo256('minecraft:brick_stairs')
stackTo256('minecraft:brick_wall')
stackTo256('minecraft:bricks')
stackTo256('minecraft:brown_bed')
stackTo256('minecraft:brown_candle')
stackTo256('minecraft:brown_carpet')
stackTo256('minecraft:brown_dye')
stackTo256('minecraft:brown_mushroom')
stackTo256('minecraft:brown_mushroom_block')
stackTo256('minecraft:brown_stained_glass')
stackTo256('minecraft:brown_stained_glass_pane')
stackTo256('minecraft:brown_terracotta')
stackTo256('minecraft:brown_wool')
stackTo256('minecraft:brush')
stackTo256('minecraft:bubble_coral_block')
stackTo256('minecraft:bucket')
stackTo256('minecraft:budding_amethyst')
stackTo256('minecraft:cactus')
stackTo256('minecraft:calcite')
stackTo256('minecraft:calibrated_sculk_sensor')
stackTo256('minecraft:camel_spawn_egg' )
stackTo256('minecraft:candle')
stackTo256('minecraft:carrot_on_a_stick')
stackTo256('minecraft:cartography_table')
stackTo256('minecraft:carved_pumpkin')
stackTo256('minecraft:cat_spawn_egg' )
stackTo256('minecraft:cauldron')
stackTo256('minecraft:cave_spider_spawn_egg' )
stackTo256('minecraft:chain')
stackTo256('minecraft:chainmail_boots')
stackTo256('minecraft:chainmail_chestplate')
stackTo256('minecraft:chainmail_helmet')
stackTo256('minecraft:chainmail_leggings')
stackTo256('minecraft:charcoal')
stackTo256('minecraft:cherry_button')
stackTo256('minecraft:cherry_door')
stackTo256('minecraft:cherry_fence')
stackTo256('minecraft:cherry_fence_gate')
stackTo256('minecraft:cherry_hanging_sign')
stackTo256('minecraft:cherry_leaves')
stackTo256('minecraft:cherry_log')
stackTo256('minecraft:cherry_planks')
stackTo256('minecraft:cherry_pressure_plate')
stackTo256('minecraft:cherry_sapling')
stackTo256('minecraft:cherry_sign')
stackTo256('minecraft:cherry_slab')
stackTo256('minecraft:cherry_stairs')
stackTo256('minecraft:cherry_trapdoor')
stackTo256('minecraft:cherry_wood')
stackTo256('minecraft:chest')
stackTo256('minecraft:chest_minecart')
stackTo256('minecraft:chicken_spawn_egg' )
stackTo256('minecraft:chiseled_bookshelf')
stackTo256('minecraft:chiseled_deepslate')
stackTo256('minecraft:chiseled_nether_bricks')
stackTo256('minecraft:chiseled_quartz_block')
stackTo256('minecraft:chiseled_red_sandstone')
stackTo256('minecraft:chiseled_sandstone')
stackTo256('minecraft:chiseled_stone_bricks')
stackTo256('minecraft:clay')
stackTo256('minecraft:clay_ball')
stackTo256('minecraft:clock')
stackTo256('minecraft:coal')
stackTo256('minecraft:coal_block')
stackTo256('minecraft:coal_ore')
stackTo256('minecraft:coarse_dirt')
stackTo256('minecraft:cobbled_deepslate_slab')
stackTo256('minecraft:cobbled_deepslate_stairs')
stackTo256('minecraft:cobbled_deepslate_wall')
stackTo256('minecraft:cobblestone')
stackTo256('minecraft:cobblestone_slab')
stackTo256('minecraft:cobblestone_stairs')
stackTo256('minecraft:cobblestone_wall')
stackTo256('minecraft:cobweb')
stackTo256('minecraft:cocoa_beans')
stackTo256('minecraft:cod_spawn_egg' )
stackTo256('minecraft:comparator')
stackTo256('minecraft:compass')
stackTo256('minecraft:composter')
stackTo256('minecraft:conduit')
stackTo256('minecraft:copper_block')
stackTo256('minecraft:copper_ingot')
stackTo256('minecraft:copper_ore')
stackTo256('minecraft:cornflower')
stackTo256('minecraft:cow_spawn_egg' )
stackTo256('minecraft:cracked_nether_bricks')
stackTo256('minecraft:cracked_polished_blackstone_bricks')
stackTo256('minecraft:cracked_stone_bricks')
stackTo256('minecraft:crafting_table')
stackTo256('minecraft:creeper_banner_pattern')
stackTo256('minecraft:creeper_head')
stackTo256('minecraft:creeper_spawn_egg' )
stackTo256('minecraft:crimson_roots')
stackTo256('minecraft:crossbow')
stackTo256('minecraft:crying_obsidian')
stackTo256('minecraft:cut_copper')
stackTo256('minecraft:cut_copper_slab')
stackTo256('minecraft:cut_copper_stairs')
stackTo256('minecraft:cut_red_sandstone')
stackTo256('minecraft:cut_red_sandstone_slab')
stackTo256('minecraft:cut_sandstone')
stackTo256('minecraft:cut_sandstone_slab')
stackTo256('minecraft:cyan_bed')
stackTo256('minecraft:cyan_candle')
stackTo256('minecraft:cyan_carpet')
stackTo256('minecraft:cyan_dye')
stackTo256('minecraft:cyan_stained_glass')
stackTo256('minecraft:cyan_stained_glass_pane')
stackTo256('minecraft:cyan_terracotta')
stackTo256('minecraft:cyan_wool')
stackTo256('minecraft:dandelion')
stackTo256('minecraft:dark_oak_button')
stackTo256('minecraft:dark_oak_door')
stackTo256('minecraft:dark_oak_fence')
stackTo256('minecraft:dark_oak_fence_gate')
stackTo256('minecraft:dark_oak_hanging_sign')
stackTo256('minecraft:dark_oak_leaves')
stackTo256('minecraft:dark_oak_log')
stackTo256('minecraft:dark_oak_planks')
stackTo256('minecraft:dark_oak_pressure_plate')
stackTo256('minecraft:dark_oak_sapling')
stackTo256('minecraft:dark_oak_sign')
stackTo256('minecraft:dark_oak_slab')
stackTo256('minecraft:dark_oak_stairs')
stackTo256('minecraft:dark_oak_trapdoor')
stackTo256('minecraft:dark_oak_wood')
stackTo256('minecraft:dark_prismarine')
stackTo256('minecraft:dark_prismarine_slab')
stackTo256('minecraft:dark_prismarine_stairs')
stackTo256('minecraft:daylight_detector')
stackTo256('minecraft:dead_bush')
stackTo256('minecraft:decorated_pot')
stackTo256('minecraft:deepslate')
stackTo256('minecraft:deepslate_tile_slab')
stackTo256('minecraft:deepslate_tile_stairs')
stackTo256('minecraft:deepslate_tile_wall')
stackTo256('minecraft:deepslate_tiles')
stackTo256('minecraft:detector_rail')
stackTo256('minecraft:diamond')
stackTo256('minecraft:diamond_axe')
stackTo256('minecraft:diamond_block')
stackTo256('minecraft:diamond_boots')
stackTo256('minecraft:diamond_chestplate')
stackTo256('minecraft:diamond_helmet')
stackTo256('minecraft:diamond_hoe')
stackTo256('minecraft:diamond_horse_armor')
stackTo256('minecraft:diamond_leggings')
stackTo256('minecraft:diamond_ore')
stackTo256('minecraft:diamond_pickaxe')
stackTo256('minecraft:diamond_shovel')
stackTo256('minecraft:diamond_sword')
stackTo256('minecraft:diorite')
stackTo256('minecraft:diorite_slab')
stackTo256('minecraft:diorite_stairs')
stackTo256('minecraft:diorite_wall')
stackTo256('minecraft:dirt')
stackTo256('minecraft:disc_fragment_5')
stackTo256('minecraft:dispenser')
stackTo256('minecraft:dolphin_spawn_egg' )
stackTo256('minecraft:donkey_spawn_egg' )
stackTo256('minecraft:dried_kelp_block')
stackTo256('minecraft:dropper')
stackTo256('minecraft:drowned_spawn_egg' )
stackTo256('minecraft:echo_shard')
stackTo256('minecraft:elder_guardian_spawn_egg' )
stackTo256('minecraft:elytra')
stackTo256('minecraft:emerald')
stackTo256('minecraft:emerald_block')
stackTo256('minecraft:ender_chest')
stackTo256('minecraft:ender_pearl')
stackTo256('minecraft:enderman_spawn_egg' )
stackTo256('minecraft:endermite_spawn_egg' )
stackTo256('minecraft:farmland')
stackTo256('minecraft:feather')
stackTo256('minecraft:fermented_spider_eye')
stackTo256('minecraft:fern')
stackTo256('minecraft:fire_charge')
stackTo256('minecraft:fire_coral_block')
stackTo256('minecraft:firework_rocket')
stackTo256('minecraft:fishing_rod')
stackTo256('minecraft:fletching_table')
stackTo256('minecraft:flint')
stackTo256('minecraft:flint_and_steel')
stackTo256('minecraft:flower_banner_pattern')
stackTo256('minecraft:flower_pot')
stackTo256('minecraft:fox_spawn_egg' )
stackTo256('minecraft:frog_spawn_egg' )
stackTo256('minecraft:frogspawn')
stackTo256('minecraft:furnace')
stackTo256('minecraft:furnace_minecart')
stackTo256('minecraft:ghast_spawn_egg' )
stackTo256('minecraft:ghast_tear')
stackTo256('minecraft:gilded_blackstone')
stackTo256('minecraft:glass')
stackTo256('minecraft:glass_pane')
stackTo256('minecraft:globe_banner_pattern')
stackTo256('minecraft:glow_ink_sac')
stackTo256('minecraft:glow_item_frame')
stackTo256('minecraft:glow_lichen')
stackTo256('minecraft:glow_squid_spawn_egg' )
stackTo256('minecraft:glowstone')
stackTo256('minecraft:glowstone_dust')
stackTo256('minecraft:goat_horn')
stackTo256('minecraft:goat_spawn_egg' )
stackTo256('minecraft:gold_block')
stackTo256('minecraft:gold_ingot')
stackTo256('minecraft:gold_nugget')
stackTo256('minecraft:gold_ore')
stackTo256('minecraft:golden_axe')
stackTo256('minecraft:golden_boots')
stackTo256('minecraft:golden_chestplate')
stackTo256('minecraft:golden_helmet')
stackTo256('minecraft:golden_hoe')
stackTo256('minecraft:golden_horse_armor')
stackTo256('minecraft:golden_leggings')
stackTo256('minecraft:golden_pickaxe')
stackTo256('minecraft:golden_shovel')
stackTo256('minecraft:golden_sword')
stackTo256('minecraft:granite')
stackTo256('minecraft:granite_slab')
stackTo256('minecraft:granite_stairs')
stackTo256('minecraft:granite_wall')
stackTo256('minecraft:grass')
stackTo256('minecraft:grass_block')
stackTo256('minecraft:gravel')
stackTo256('minecraft:gray_bed')
stackTo256('minecraft:gray_candle')
stackTo256('minecraft:gray_carpet')
stackTo256('minecraft:gray_dye')
stackTo256('minecraft:gray_stained_glass')
stackTo256('minecraft:gray_terracotta')
stackTo256('minecraft:gray_wool')
stackTo256('minecraft:green_bed')
stackTo256('minecraft:green_candle')
stackTo256('minecraft:green_carpet')
stackTo256('minecraft:green_dye')
stackTo256('minecraft:green_stained_glass')
stackTo256('minecraft:green_stained_glass_pane')
stackTo256('minecraft:green_terracotta')
stackTo256('minecraft:green_wool')
stackTo256('minecraft:guardian_spawn_egg' )
stackTo256('minecraft:gunpowder')
stackTo256('minecraft:hanging_roots')
stackTo256('minecraft:hay_block')
stackTo256('minecraft:heart_of_the_sea')
stackTo256('minecraft:heavy_weighted_pressure_plate')
stackTo256('minecraft:honey_block')
stackTo256('minecraft:honeycomb')
stackTo256('minecraft:honeycomb_block')
stackTo256('minecraft:hopper')
stackTo256('minecraft:hopper_minecart')
stackTo256('minecraft:horn_coral_block')
stackTo256('minecraft:horse_spawn_egg' )
stackTo256('minecraft:husk_spawn_egg' )
stackTo256('minecraft:ice')
stackTo256('minecraft:infested_chiseled_stone_bricks')
stackTo256('minecraft:infested_cobblestone')
stackTo256('minecraft:infested_cracked_stone_bricks')
stackTo256('minecraft:infested_deepslate')
stackTo256('minecraft:infested_mossy_stone_bricks')
stackTo256('minecraft:infested_stone')
stackTo256('minecraft:infested_stone_bricks')
stackTo256('minecraft:ink_sac')
stackTo256('minecraft:iron_axe')
stackTo256('minecraft:iron_bars')
stackTo256('minecraft:iron_block')
stackTo256('minecraft:iron_boots')
stackTo256('minecraft:iron_chestplate')
stackTo256('minecraft:iron_door')
stackTo256('minecraft:iron_golem_spawn_egg' )
stackTo256('minecraft:iron_helmet')
stackTo256('minecraft:iron_hoe')
stackTo256('minecraft:iron_horse_armor')
stackTo256('minecraft:iron_ingot')
stackTo256('minecraft:iron_leggings')
stackTo256('minecraft:iron_nugget')
stackTo256('minecraft:iron_ore')
stackTo256('minecraft:iron_pickaxe')
stackTo256('minecraft:iron_shovel')
stackTo256('minecraft:iron_sword')
stackTo256('minecraft:iron_trapdoor')
stackTo256('minecraft:item_frame')
stackTo256('minecraft:jack_o_lantern')
stackTo256('minecraft:jukebox')
stackTo256('minecraft:jungle_button')
stackTo256('minecraft:jungle_door')
stackTo256('minecraft:jungle_fence')
stackTo256('minecraft:jungle_fence_gate')
stackTo256('minecraft:jungle_hanging_sign')
stackTo256('minecraft:jungle_leaves')
stackTo256('minecraft:jungle_log')
stackTo256('minecraft:jungle_planks')
stackTo256('minecraft:jungle_pressure_plate')
stackTo256('minecraft:jungle_sapling')
stackTo256('minecraft:jungle_sign')
stackTo256('minecraft:jungle_slab')
stackTo256('minecraft:jungle_stairs')
stackTo256('minecraft:jungle_trapdoor')
stackTo256('minecraft:jungle_wood')
stackTo256('minecraft:kelp')
stackTo256('minecraft:ladder')
stackTo256('minecraft:lapis_block')
stackTo256('minecraft:lapis_lazuli')
stackTo256('minecraft:lapis_ore')
stackTo256('minecraft:large_amethyst_bud')
stackTo256('minecraft:large_fern')
stackTo256('minecraft:lava_bucket')
stackTo256('minecraft:lead')
stackTo256('minecraft:leather')
stackTo256('minecraft:leather_boots')
stackTo256('minecraft:leather_chestplate')
stackTo256('minecraft:leather_helmet')
stackTo256('minecraft:leather_horse_armor')
stackTo256('minecraft:leather_leggings')
stackTo256('minecraft:lectern')
stackTo256('minecraft:lever')
stackTo256('minecraft:light_blue_bed')
stackTo256('minecraft:light_blue_candle')
stackTo256('minecraft:light_blue_carpet')
stackTo256('minecraft:light_blue_dye')
stackTo256('minecraft:light_blue_stained_glass')
stackTo256('minecraft:light_blue_stained_glass_pane')
stackTo256('minecraft:light_blue_terracotta')
stackTo256('minecraft:light_blue_wool')
stackTo256('minecraft:light_gray_bed')
stackTo256('minecraft:light_gray_candle')
stackTo256('minecraft:light_gray_carpet')
stackTo256('minecraft:light_gray_dye')
stackTo256('minecraft:light_gray_stained_glass')
stackTo256('minecraft:light_gray_stained_glass_pane')
stackTo256('minecraft:light_gray_terracotta')
stackTo256('minecraft:light_gray_wool')
stackTo256('minecraft:light_weighted_pressure_plate')
stackTo256('minecraft:lightning_rod')
stackTo256('minecraft:lilac')
stackTo256('minecraft:lily_of_the_valley')
stackTo256('minecraft:lily_pad')
stackTo256('minecraft:lime_bed')
stackTo256('minecraft:lime_candle')
stackTo256('minecraft:lime_carpet')
stackTo256('minecraft:lime_dye')
stackTo256('minecraft:lime_stained_glass')
stackTo256('minecraft:lime_stained_glass_pane')
stackTo256('minecraft:lime_terracotta')
stackTo256('minecraft:lime_wool')
stackTo256('minecraft:llama_spawn_egg' )
stackTo256('minecraft:lodestone')
stackTo256('minecraft:loom')
stackTo256('minecraft:magenta_bed')
stackTo256('minecraft:magenta_candle')
stackTo256('minecraft:magenta_carpet')
stackTo256('minecraft:magenta_dye')
stackTo256('minecraft:magenta_stained_glass')
stackTo256('minecraft:magenta_stained_glass_pane')
stackTo256('minecraft:magenta_terracotta')
stackTo256('minecraft:magenta_wool')
stackTo256('minecraft:magma_block')
stackTo256('minecraft:magma_cream')
stackTo256('minecraft:magma_cube_spawn_egg' )
stackTo256('minecraft:mangrove_button')
stackTo256('minecraft:mangrove_door')
stackTo256('minecraft:mangrove_fence')
stackTo256('minecraft:mangrove_fence_gate')
stackTo256('minecraft:mangrove_hanging_sign')
stackTo256('minecraft:mangrove_leaves')
stackTo256('minecraft:mangrove_log')
stackTo256('minecraft:mangrove_planks')
stackTo256('minecraft:mangrove_pressure_plate')
stackTo256('minecraft:mangrove_propagule')
stackTo256('minecraft:mangrove_sign')
stackTo256('minecraft:mangrove_slab')
stackTo256('minecraft:mangrove_stairs')
stackTo256('minecraft:mangrove_trapdoor')
stackTo256('minecraft:mangrove_wood')
stackTo256('minecraft:map')
stackTo256('minecraft:medium_amethyst_bud')
stackTo256('minecraft:melon')
stackTo256('minecraft:melon_seeds')
stackTo256('minecraft:milk_bucket')
stackTo256('minecraft:minecart')
stackTo256('minecraft:mojang_banner_pattern')
stackTo256('minecraft:mooshroom_spawn_egg' )
stackTo256('minecraft:moss_block')
stackTo256('minecraft:moss_carpet')
stackTo256('minecraft:mossy_cobblestone')
stackTo256('minecraft:mossy_cobblestone_slab')
stackTo256('minecraft:mossy_cobblestone_stairs')
stackTo256('minecraft:mossy_cobblestone_wall')
stackTo256('minecraft:mossy_stone_brick_slab')
stackTo256('minecraft:mossy_stone_brick_stairs')
stackTo256('minecraft:mossy_stone_brick_wall')
stackTo256('minecraft:mossy_stone_bricks')
stackTo256('minecraft:mud')
stackTo256('minecraft:mud_brick_slab')
stackTo256('minecraft:mud_brick_stairs')
stackTo256('minecraft:mud_brick_wall')
stackTo256('minecraft:mud_bricks')
stackTo256('minecraft:mule_spawn_egg' )
stackTo256('minecraft:mushroom_stem')
stackTo256('minecraft:music_disc_11')
stackTo256('minecraft:music_disc_13')
stackTo256('minecraft:music_disc_5')
stackTo256('minecraft:music_disc_blocks')
stackTo256('minecraft:music_disc_cat')
stackTo256('minecraft:music_disc_chirp')
stackTo256('minecraft:music_disc_far')
stackTo256('minecraft:music_disc_mall')
stackTo256('minecraft:music_disc_mellohi')
stackTo256('minecraft:music_disc_otherside')
stackTo256('minecraft:music_disc_pigstep')
stackTo256('minecraft:music_disc_relic')
stackTo256('minecraft:music_disc_stal')
stackTo256('minecraft:music_disc_strad')
stackTo256('minecraft:music_disc_wait')
stackTo256('minecraft:music_disc_ward')
stackTo256('minecraft:mycelium')
stackTo256('minecraft:name_tag')
stackTo256('minecraft:nautilus_shell')
stackTo256('minecraft:nether_brick')
stackTo256('minecraft:nether_brick_fence')
stackTo256('minecraft:nether_brick_slab')
stackTo256('minecraft:nether_brick_stairs')
stackTo256('minecraft:nether_brick_wall')
stackTo256('minecraft:nether_bricks')
stackTo256('minecraft:nether_gold_ore')
stackTo256('minecraft:nether_quartz_ore')
stackTo256('minecraft:nether_star')
stackTo256('minecraft:nether_wart')
stackTo256('minecraft:netherite_scrap')
stackTo256('minecraft:netherrack')
stackTo256('minecraft:note_block')
stackTo256('minecraft:oak_boat')
stackTo256('minecraft:oak_button')
stackTo256('minecraft:oak_chest_boat')
stackTo256('minecraft:oak_door')
stackTo256('minecraft:oak_fence')
stackTo256('minecraft:oak_fence_gate')
stackTo256('minecraft:oak_hanging_sign')
stackTo256('minecraft:oak_leaves')
stackTo256('minecraft:oak_log')
stackTo256('minecraft:oak_planks')
stackTo256('minecraft:oak_pressure_plate')
stackTo256('minecraft:oak_sapling')
stackTo256('minecraft:oak_sign')
stackTo256('minecraft:oak_slab')
stackTo256('minecraft:oak_stairs')
stackTo256('minecraft:oak_trapdoor')
stackTo256('minecraft:oak_wood')
stackTo256('minecraft:observer')
stackTo256('minecraft:obsidian')
stackTo256('minecraft:ocelot_spawn_egg' )
stackTo256('minecraft:ochre_froglight')
stackTo256('minecraft:orange_bed')
stackTo256('minecraft:orange_candle')
stackTo256('minecraft:orange_carpet')
stackTo256('minecraft:orange_dye')
stackTo256('minecraft:orange_stained_glass')
stackTo256('minecraft:orange_stained_glass_pane')
stackTo256('minecraft:orange_terracotta')
stackTo256('minecraft:orange_tulip')
stackTo256('minecraft:orange_wool')
stackTo256('minecraft:oxeye_daisy')
stackTo256('minecraft:packed_ice')
stackTo256('minecraft:packed_mud')
stackTo256('minecraft:painting')
stackTo256('minecraft:panda_spawn_egg' )
stackTo256('minecraft:paper')
stackTo256('minecraft:parrot_spawn_egg' )
stackTo256('minecraft:pearlescent_froglight')
stackTo256('minecraft:peony')
stackTo256('minecraft:phantom_membrane')
stackTo256('minecraft:phantom_spawn_egg' )
stackTo256('minecraft:pig_spawn_egg' )
stackTo256('minecraft:piglin_banner_pattern')
stackTo256('minecraft:pink_bed')
stackTo256('minecraft:pink_candle')
stackTo256('minecraft:pink_carpet')
stackTo256('minecraft:pink_dye')
stackTo256('minecraft:pink_petals')
stackTo256('minecraft:pink_stained_glass')
stackTo256('minecraft:pink_stained_glass_pane')
stackTo256('minecraft:pink_terracotta')
stackTo256('minecraft:pink_tulip')
stackTo256('minecraft:pink_wool')
stackTo256('minecraft:piston')
stackTo256('minecraft:pitcher_plant')
stackTo256('minecraft:pitcher_pod')
stackTo256('minecraft:player_head')
stackTo256('minecraft:podzol')
stackTo256('minecraft:polar_bear_spawn_egg' )
stackTo256('minecraft:polished_basalt')
stackTo256('minecraft:polished_blackstone_brick_slab')
stackTo256('minecraft:polished_blackstone_brick_stairs')
stackTo256('minecraft:polished_blackstone_brick_wall')
stackTo256('minecraft:polished_blackstone_bricks')
stackTo256('minecraft:poppy')
stackTo256('minecraft:powder_snow_bucket')
stackTo256('minecraft:powered_rail')
stackTo256('minecraft:prismarine')
stackTo256('minecraft:prismarine_brick_slab')
stackTo256('minecraft:prismarine_brick_stairs')
stackTo256('minecraft:prismarine_bricks')
stackTo256('minecraft:prismarine_crystals')
stackTo256('minecraft:prismarine_shard')
stackTo256('minecraft:prismarine_slab')
stackTo256('minecraft:prismarine_stairs')
stackTo256('minecraft:prismarine_wall')
stackTo256('minecraft:pumpkin')
stackTo256('minecraft:pumpkin_seeds')
stackTo256('minecraft:purple_bed')
stackTo256('minecraft:purple_candle')
stackTo256('minecraft:purple_carpet')
stackTo256('minecraft:purple_dye')
stackTo256('minecraft:purple_stained_glass')
stackTo256('minecraft:purple_stained_glass_pane')
stackTo256('minecraft:purple_terracotta')
stackTo256('minecraft:purple_wool')
stackTo256('minecraft:purpur_block')
stackTo256('minecraft:purpur_pillar')
stackTo256('minecraft:purpur_slab')
stackTo256('minecraft:purpur_stairs')
stackTo256('minecraft:quartz')
stackTo256('minecraft:quartz_block')
stackTo256('minecraft:quartz_bricks')
stackTo256('minecraft:quartz_pillar')
stackTo256('minecraft:quartz_slab')
stackTo256('minecraft:quartz_stairs')
stackTo256('minecraft:rail')
stackTo256('minecraft:ravager_spawn_egg' )
stackTo256('minecraft:raw_copper')
stackTo256('minecraft:raw_copper_block')
stackTo256('minecraft:raw_gold')
stackTo256('minecraft:raw_gold_block')
stackTo256('minecraft:raw_iron')
stackTo256('minecraft:raw_iron_block')
stackTo256('minecraft:recovery_compass')
stackTo256('minecraft:red_bed')
stackTo256('minecraft:red_candle')
stackTo256('minecraft:red_carpet')
stackTo256('minecraft:red_dye')
stackTo256('minecraft:red_mushroom')
stackTo256('minecraft:red_mushroom_block')
stackTo256('minecraft:red_sand')
stackTo256('minecraft:red_sandstone')
stackTo256('minecraft:red_sandstone_slab')
stackTo256('minecraft:red_sandstone_stairs')
stackTo256('minecraft:red_sandstone_wall')
stackTo256('minecraft:red_stained_glass')
stackTo256('minecraft:red_stained_glass_pane')
stackTo256('minecraft:red_terracotta')
stackTo256('minecraft:red_tulip')
stackTo256('minecraft:red_wool')
stackTo256('minecraft:redstone')
stackTo256('minecraft:redstone_block')
stackTo256('minecraft:redstone_lamp')
stackTo256('minecraft:redstone_ore')
stackTo256('minecraft:redstone_torch')
stackTo256('minecraft:reinforced_deepslate')
stackTo256('minecraft:repeater')
stackTo256('minecraft:respawn_anchor')
stackTo256('minecraft:rooted_dirt')
stackTo256('minecraft:rose_bush')
stackTo256('minecraft:saddle')
stackTo256('minecraft:salmon_spawn_egg' )
stackTo256('minecraft:sand')
stackTo256('minecraft:sandstone')
stackTo256('minecraft:sandstone_slab')
stackTo256('minecraft:sandstone_stairs')
stackTo256('minecraft:sandstone_wall')
stackTo256('minecraft:scaffolding')
stackTo256('minecraft:sculk')
stackTo256('minecraft:sculk_catalyst')
stackTo256('minecraft:sculk_sensor')
stackTo256('minecraft:sculk_shrieker')
stackTo256('minecraft:sculk_vein')
stackTo256('minecraft:scute')
stackTo256('minecraft:sea_lantern')
stackTo256('minecraft:sea_pickle')
stackTo256('minecraft:seagrass')
stackTo256('minecraft:shears')
stackTo256('minecraft:sheep_spawn_egg' )
stackTo256('minecraft:shroomlight')
stackTo256('minecraft:silverfish_spawn_egg' )
stackTo256('minecraft:skeleton_horse_spawn_egg' )
stackTo256('minecraft:skeleton_skull')
stackTo256('minecraft:skeleton_spawn_egg' )
stackTo256('minecraft:skull_banner_pattern')
stackTo256('minecraft:slime_ball')
stackTo256('minecraft:slime_block')
stackTo256('minecraft:slime_spawn_egg' )
stackTo256('minecraft:small_amethyst_bud')
stackTo256('minecraft:small_dripleaf')
stackTo256('minecraft:smooth_basalt')
stackTo256('minecraft:smooth_quartz')
stackTo256('minecraft:smooth_quartz_slab')
stackTo256('minecraft:smooth_quartz_stairs')
stackTo256('minecraft:smooth_red_sandstone')
stackTo256('minecraft:smooth_red_sandstone_slab')
stackTo256('minecraft:smooth_red_sandstone_stairs')
stackTo256('minecraft:smooth_sandstone')
stackTo256('minecraft:smooth_sandstone_slab')
stackTo256('minecraft:smooth_sandstone_stairs')
stackTo256('minecraft:smooth_stone')
stackTo256('minecraft:smooth_stone_slab')
stackTo256('minecraft:snow')
stackTo256('minecraft:snow_block')
stackTo256('minecraft:snow_golem_spawn_egg' )
stackTo256('minecraft:snowball')
stackTo256('minecraft:soul_sand')
stackTo256('minecraft:soul_soil')
stackTo256('minecraft:soul_torch')
stackTo256('minecraft:spawner' )
stackTo256('minecraft:spectral_arrow')
stackTo256('minecraft:spider_spawn_egg' )
stackTo256('minecraft:sponge')
stackTo256('minecraft:spore_blossom')
stackTo256('minecraft:spruce_button')
stackTo256('minecraft:spruce_door')
stackTo256('minecraft:spruce_fence')
stackTo256('minecraft:spruce_fence_gate')
stackTo256('minecraft:spruce_hanging_sign')
stackTo256('minecraft:spruce_leaves')
stackTo256('minecraft:spruce_log')
stackTo256('minecraft:spruce_planks')
stackTo256('minecraft:spruce_pressure_plate')
stackTo256('minecraft:spruce_sapling')
stackTo256('minecraft:spruce_sign')
stackTo256('minecraft:spruce_slab')
stackTo256('minecraft:spruce_stairs')
stackTo256('minecraft:spruce_trapdoor')
stackTo256('minecraft:spruce_wood')
stackTo256('minecraft:spyglass')
stackTo256('minecraft:squid_spawn_egg' )
stackTo256('minecraft:stick')
stackTo256('minecraft:sticky_piston')
stackTo256('minecraft:stone')
stackTo256('minecraft:stone_brick_slab')
stackTo256('minecraft:stone_brick_stairs')
stackTo256('minecraft:stone_brick_wall')
stackTo256('minecraft:stone_bricks')
stackTo256('minecraft:stone_button')
stackTo256('minecraft:stone_pickaxe')
stackTo256('minecraft:stone_pressure_plate')
stackTo256('minecraft:stone_slab')
stackTo256('minecraft:stone_stairs')
stackTo256('minecraft:stonecutter')
stackTo256('minecraft:stray_spawn_egg' )
stackTo256('minecraft:strider_spawn_egg' )
stackTo256('minecraft:string')
stackTo256('minecraft:stripped_acacia_log')
stackTo256('minecraft:stripped_acacia_wood')
stackTo256('minecraft:stripped_bamboo_block')
stackTo256('minecraft:stripped_birch_log')
stackTo256('minecraft:stripped_birch_wood')
stackTo256('minecraft:stripped_cherry_log')
stackTo256('minecraft:stripped_cherry_wood')
stackTo256('minecraft:stripped_dark_oak_log')
stackTo256('minecraft:stripped_dark_oak_wood')
stackTo256('minecraft:stripped_jungle_log')
stackTo256('minecraft:stripped_jungle_wood')
stackTo256('minecraft:stripped_mangrove_log')
stackTo256('minecraft:stripped_mangrove_wood')
stackTo256('minecraft:stripped_oak_log')
stackTo256('minecraft:stripped_oak_wood')
stackTo256('minecraft:stripped_spruce_log')
stackTo256('minecraft:stripped_spruce_wood')
stackTo256('minecraft:sugar')
stackTo256('minecraft:sugar_cane')
stackTo256('minecraft:sunflower')
stackTo256('minecraft:tadpole_spawn_egg' )
stackTo256('minecraft:tall_grass')
stackTo256('minecraft:target')
stackTo256('minecraft:terracotta')
stackTo256('minecraft:tinted_glass')
stackTo256('minecraft:tnt')
stackTo256('minecraft:tnt_minecart')
stackTo256('minecraft:torchflower')
stackTo256('minecraft:torchflower_seeds')
stackTo256('minecraft:trapped_chest')
stackTo256('minecraft:trident')
stackTo256('minecraft:tripwire_hook')
stackTo256('minecraft:tropical_fish_spawn_egg' )
stackTo256('minecraft:tube_coral_block')
stackTo256('minecraft:tuff')
stackTo256('minecraft:turtle_egg')
stackTo256('minecraft:turtle_helmet')
stackTo256('minecraft:turtle_spawn_egg' )
stackTo256('minecraft:verdant_froglight')
stackTo256('minecraft:vex_spawn_egg' )
stackTo256('minecraft:vine')
stackTo256('minecraft:warden_spawn_egg' )
stackTo256('minecraft:warped_fungus_on_a_stick')
stackTo256('minecraft:water_bucket')
stackTo256('minecraft:wet_sponge')
stackTo256('minecraft:wheat')
stackTo256('minecraft:wheat_seeds')
stackTo256('minecraft:white_bed')
stackTo256('minecraft:white_candle')
stackTo256('minecraft:white_carpet')
stackTo256('minecraft:white_dye')
stackTo256('minecraft:white_stained_glass')
stackTo256('minecraft:white_stained_glass_pane')
stackTo256('minecraft:white_terracotta')
stackTo256('minecraft:white_tulip')
stackTo256('minecraft:white_wool')
stackTo256('minecraft:wither_rose')
stackTo256('minecraft:wither_skeleton_skull')
stackTo256('minecraft:wither_skeleton_spawn_egg' )
stackTo256('minecraft:wolf_spawn_egg' )
stackTo256('minecraft:wooden_axe')
stackTo256('minecraft:wooden_hoe')
stackTo256('minecraft:wooden_pickaxe')
stackTo256('minecraft:wooden_shovel')
stackTo256('minecraft:wooden_sword')
stackTo256('minecraft:writable_book')
stackTo256('minecraft:yellow_bed')
stackTo256('minecraft:yellow_candle')
stackTo256('minecraft:yellow_carpet')
stackTo256('minecraft:yellow_dye')
stackTo256('minecraft:yellow_stained_glass')
stackTo256('minecraft:yellow_stained_glass_pane')
stackTo256('minecraft:yellow_terracotta')
stackTo256('minecraft:yellow_wool')
stackTo256('minecraft:zombie_head')
stackTo256('minecraft:zombie_horse_spawn_egg' )
stackTo256('minecraft:zombie_spawn_egg' )
stackTo256('moreminecarts:maglev_powered_rail')
stackTo256('moreminecarts:maglev_rail')
stackTo256('moyai:moyai')
stackTo256('pet_cemetery:pet_collar')
stackTo256('pet_cemetery:skeleton_cat_spawn_egg' )
stackTo256('pet_cemetery:skeleton_parrot_spawn_egg' )
stackTo256('pet_cemetery:skeleton_wolf_spawn_egg' )
stackTo256('pet_cemetery:zombie_cat_spawn_egg' )
stackTo256('pet_cemetery:zombie_parrot_spawn_egg' )
stackTo256('pet_cemetery:zombie_wolf_spawn_egg')
stackTo256('quark:abacus')
stackTo256('quark:backpack')
stackTo256('quark:chute')
stackTo256('quark:crafter')
stackTo256('quark:ender_watcher')
stackTo256('quark:glow_lichen_growth')
stackTo256('quark:glow_shroom')
stackTo256('quark:glow_shroom_block')
stackTo256('quark:glow_shroom_ring')
stackTo256('quark:glow_shroom_stem')
stackTo256('quark:gold_button')
stackTo256('quark:gravisand')
stackTo256('quark:iron_button')
stackTo256('quark:iron_rod')
stackTo256('quark:limestone')
stackTo256('quark:limestone_bricks')
stackTo256('quark:limestone_bricks_slab')
stackTo256('quark:limestone_bricks_stairs')
stackTo256('quark:limestone_bricks_wall')
stackTo256('quark:limestone_slab')
stackTo256('quark:limestone_stairs')
stackTo256('quark:limestone_wall')
stackTo256('quark:magnet')
stackTo256('quark:monster_box' )
stackTo256('quark:music_disc_chatter')
stackTo256('quark:music_disc_clock')
stackTo256('quark:music_disc_crickets')
stackTo256('quark:music_disc_drips')
stackTo256('quark:music_disc_fire')
stackTo256('quark:music_disc_ocean')
stackTo256('quark:music_disc_rain')
stackTo256('quark:music_disc_wind')
stackTo256('quark:obsidian_pressure_plate')
stackTo256('quark:paper_wall')
stackTo256('quark:pipe')
stackTo256('quark:redstone_randomizer')
stackTo256('quark:shale')
stackTo256('quark:shale_bricks')
stackTo256('quark:shale_bricks_slab')
stackTo256('quark:shale_bricks_stairs')
stackTo256('quark:shale_bricks_wall')
stackTo256('quark:shale_slab')
stackTo256('quark:shale_stairs')
stackTo256('quark:shale_wall')
stackTo256('quark:stick_block')
stackTo256('quark:sturdy_stone')
stackTo256('quark:tiny_potato')
stackTo256('quark:wraith_spawn_egg' )
stackTo256('rediscovered:ancient_cherry_leaves')
stackTo256('rediscovered:ancient_cherry_sapling')
stackTo256('rediscovered:ancient_crying_obsidian')
stackTo256('rediscovered:bright_green_carpet')
stackTo256('rediscovered:bright_green_wool')
stackTo256('rediscovered:brittle_mud_bricks')
stackTo256('rediscovered:brittle_packed_mud')
stackTo256('rediscovered:cyan_rose')
stackTo256('rediscovered:dragon_altar')
stackTo256('rediscovered:dragon_armor')
stackTo256('rediscovered:fish_spawn_egg' )
stackTo256('rediscovered:gear')
stackTo256('rediscovered:glowing_obsidian')
stackTo256('rediscovered:large_brick_slab')
stackTo256('rediscovered:large_brick_stairs')
stackTo256('rediscovered:large_brick_wall')
stackTo256('rediscovered:large_bricks')
stackTo256('rediscovered:lavender_carpet')
stackTo256('rediscovered:lavender_wool')
stackTo256('rediscovered:mini_dragon_pylon')
stackTo256('rediscovered:music_disc_calm4')
stackTo256('rediscovered:nether_reactor_core')
stackTo256('rediscovered:obsidian_bulb')
stackTo256('rediscovered:paeonia')
stackTo256('rediscovered:pigman_spawn_egg' )
stackTo256('rediscovered:plate_boots')
stackTo256('rediscovered:plate_chestplate')
stackTo256('rediscovered:plate_helmet')
stackTo256('rediscovered:plate_leggings')
stackTo256('rediscovered:purple_arrow')
stackTo256('rediscovered:quiver')
stackTo256('rediscovered:rana_spawn_egg' )
stackTo256('rediscovered:red_dragon_egg')
stackTo256('rediscovered:rose')
stackTo256('rediscovered:rose_carpet')
stackTo256('rediscovered:rose_wool')
stackTo256('rediscovered:rotational_converter')
stackTo256('rediscovered:ruby')
stackTo256('rediscovered:ruby_eye')
stackTo256('rediscovered:ruby_flute')
stackTo256('rediscovered:ruby_ore')
stackTo256('rediscovered:scarecrow')
stackTo256('rediscovered:sky_blue_carpet')
stackTo256('rediscovered:sky_blue_wool')
stackTo256('rediscovered:slate_blue_carpet')
stackTo256('rediscovered:slate_blue_wool')
stackTo256('rediscovered:spikes')
stackTo256('rediscovered:spring_green_carpet')
stackTo256('rediscovered:spring_green_wool')
stackTo256('rediscovered:steve_spawn_egg' )
stackTo256('rediscovered:studded_boots')
stackTo256('rediscovered:studded_chestplate')
stackTo256('rediscovered:studded_helmet')
stackTo256('rediscovered:studded_leggings')
stackTo256('rediscovered:zombie_pigman_spawn_egg' )
stackTo256('savage_and_ravage:mask_of_dishonesty')
stackTo256('snowpig:snow_pig_spawn_egg' )
stackTo256('snowyspirit:glow_lights_prismatic')
stackTo256('snowyspirit:snow_globe')
stackTo256('snowyspirit:wreath')
stackTo256('species:deepfish_spawn_egg' )
stackTo256('species:limpet_spawn_egg' )
stackTo256('spelunkery:black_glowstick')
stackTo256('spelunkery:blue_glowstick')
stackTo256('spelunkery:brown_glowstick')
stackTo256('spelunkery:bunny_ears')
stackTo256('spelunkery:button_mushroom')
stackTo256('spelunkery:cave_mushroom_stem')
stackTo256('spelunkery:compression_blast_miner')
stackTo256('spelunkery:copper_nugget')
stackTo256('spelunkery:crimini')
stackTo256('spelunkery:cyan_glowstick')
stackTo256('spelunkery:dust_bun')
stackTo256('spelunkery:echo_fork')
stackTo256('spelunkery:glowstick')
stackTo256('spelunkery:gray_glowstick')
stackTo256('spelunkery:green_glowstick')
stackTo256('spelunkery:grilled_portabella')
stackTo256('spelunkery:inkcap_mushroom')
stackTo256('spelunkery:inkcap_mushroom_block')
stackTo256('spelunkery:item_magnet')
stackTo256('spelunkery:light_blue_glowstick')
stackTo256('spelunkery:light_gray_glowstick')
stackTo256('spelunkery:lime_glowstick')
stackTo256('spelunkery:magenta_glowstick')
stackTo256('spelunkery:milly_bubcap')
stackTo256('spelunkery:milly_bubcap_block')
stackTo256('spelunkery:mushgloom')
stackTo256('spelunkery:mushgloom_block')
stackTo256('spelunkery:orange_glowstick')
stackTo256('spelunkery:phosphor_fungus')
stackTo256('spelunkery:phosphor_fungus_block')
stackTo256('spelunkery:phosphor_shroomlight')
stackTo256('spelunkery:pink_glowstick')
stackTo256('spelunkery:portabella')
stackTo256('spelunkery:portabella_block')
stackTo256('spelunkery:purple_glowstick')
stackTo256('spelunkery:raw_magnetite')
stackTo256('spelunkery:raw_magnetite_block')
stackTo256('spelunkery:red_glowstick')
stackTo256('spelunkery:rope_ladder')
stackTo256('spelunkery:sporophyte')
stackTo256('spelunkery:tall_sporophyte')
stackTo256('spelunkery:tangle_roots')
stackTo256('spelunkery:tangle_roots_block')
stackTo256('spelunkery:tuning_fork')
stackTo256('spelunkery:white_glowstick')
stackTo256('spelunkery:white_inkcap_mushroom')
stackTo256('spelunkery:white_inkcap_mushroom_block')
stackTo256('spelunkery:wooden_rail')
stackTo256('spelunkery:yellow_glowstick')
stackTo256('supplementaries:altimeter')
stackTo256('supplementaries:ash')
stackTo256('supplementaries:ash_brick')
stackTo256('supplementaries:ash_bricks')
stackTo256('supplementaries:ash_bricks_slab')
stackTo256('supplementaries:ash_bricks_stairs')
stackTo256('supplementaries:ash_bricks_wall')
stackTo256('supplementaries:bellows')
stackTo256('supplementaries:blackboard')
stackTo256('supplementaries:bubble_block')
stackTo256('supplementaries:bubble_blower')
stackTo256('supplementaries:bunting',)
stackTo256('supplementaries:cartographers_quill')
stackTo256('supplementaries:checker_block')
stackTo256('supplementaries:checker_slab')
stackTo256('supplementaries:clock_block')
stackTo256('supplementaries:crank')
stackTo256('supplementaries:crystal_display')
stackTo256('supplementaries:dispenser_minecart')
stackTo256('supplementaries:doormat')
stackTo256('supplementaries:enderman_head')
stackTo256('supplementaries:feather_block')
stackTo256('supplementaries:flag_black')
stackTo256('supplementaries:flag_blue')
stackTo256('supplementaries:flag_brown')
stackTo256('supplementaries:flag_cyan')
stackTo256('supplementaries:flag_gray')
stackTo256('supplementaries:flag_green')
stackTo256('supplementaries:flag_light_blue')
stackTo256('supplementaries:flag_light_gray')
stackTo256('supplementaries:flag_lime')
stackTo256('supplementaries:flag_magenta')
stackTo256('supplementaries:flag_orange')
stackTo256('supplementaries:flag_pink')
stackTo256('supplementaries:flag_purple')
stackTo256('supplementaries:flag_red')
stackTo256('supplementaries:flag_white')
stackTo256('supplementaries:flag_yellow')
stackTo256('supplementaries:flint_block')
stackTo256('supplementaries:flute')
stackTo256('supplementaries:gold_door')
stackTo256('supplementaries:hat_stand')
stackTo256('supplementaries:iron_gate')
stackTo256('supplementaries:key')
stackTo256('supplementaries:lock_block')
stackTo256('supplementaries:netherite_door')
stackTo256('supplementaries:netherite_trapdoor')
stackTo256('supplementaries:notice_board')
stackTo256('supplementaries:pulley_block')
stackTo256('supplementaries:raked_gravel')
stackTo256('supplementaries:redstone_illuminator')
stackTo256('supplementaries:relayer')
stackTo256('supplementaries:rope')
stackTo256('supplementaries:sack')
stackTo256('supplementaries:slice_map')
stackTo256('supplementaries:slingshot')
stackTo256('supplementaries:soap')
stackTo256('supplementaries:soap_block')
stackTo256('supplementaries:speaker_block')
stackTo256('supplementaries:spring_launcher')
stackTo256('supplementaries:statue')
stackTo256('supplementaries:sugar_cube')
stackTo256('supplementaries:turn_table')
stackTo256('supplementaries:wind_vane')
stackTo256('supplementaries:wrench')
stackTo256('sweety_garden:baileya')
stackTo256('sweety_garden:cyan_poppy')
stackTo256('sweety_garden:hepatica')
stackTo256('sweety_garden:passion_flower')
stackTo256('sweety_garden:pontederia')
stackTo256('sweety_garden:purple_shamrock')
stackTo256('sweety_garden:wood_anemone')
stackTo256('sweety_garden:wood_sorrel')
stackTo256('upgrade_aquatic:acan_coral_block')
stackTo256('upgrade_aquatic:branch_coral_block')
stackTo256('upgrade_aquatic:chrome_coral_block')
stackTo256('upgrade_aquatic:disc_fragment_atlantis')
stackTo256('upgrade_aquatic:driftwood')
stackTo256('upgrade_aquatic:driftwood_button')
stackTo256('upgrade_aquatic:driftwood_door')
stackTo256('upgrade_aquatic:driftwood_fence')
stackTo256('upgrade_aquatic:driftwood_fence_gate')
stackTo256('upgrade_aquatic:driftwood_hanging_sign')
stackTo256('upgrade_aquatic:driftwood_log')
stackTo256('upgrade_aquatic:driftwood_planks')
stackTo256('upgrade_aquatic:driftwood_pressure_plate')
stackTo256('upgrade_aquatic:driftwood_sign')
stackTo256('upgrade_aquatic:driftwood_slab')
stackTo256('upgrade_aquatic:driftwood_stairs')
stackTo256('upgrade_aquatic:driftwood_trapdoor')
stackTo256('upgrade_aquatic:elder_eye')
stackTo256('upgrade_aquatic:embedded_ammonite')
stackTo256('upgrade_aquatic:finger_coral_block')
stackTo256('upgrade_aquatic:goose_spawn_egg' )
stackTo256('upgrade_aquatic:kelp_block')
stackTo256('upgrade_aquatic:moss_coral_block')
stackTo256('upgrade_aquatic:mulberry_jam_block')
stackTo256('upgrade_aquatic:music_disc_atlantis')
stackTo256('upgrade_aquatic:nautilus_spawn_egg' )
stackTo256('upgrade_aquatic:petal_coral_block')
stackTo256('upgrade_aquatic:pike_spawn_egg' )
stackTo256('upgrade_aquatic:pillow_coral_block')
stackTo256('upgrade_aquatic:pink_searocket')
stackTo256('upgrade_aquatic:prismarine_coral_block')
stackTo256('upgrade_aquatic:prismarine_rod')
stackTo256('upgrade_aquatic:prismarine_rod_bundle')
stackTo256('upgrade_aquatic:river_button')
stackTo256('upgrade_aquatic:river_door')
stackTo256('upgrade_aquatic:river_fence')
stackTo256('upgrade_aquatic:river_fence_gate')
stackTo256('upgrade_aquatic:river_hanging_sign')
stackTo256('upgrade_aquatic:river_log')
stackTo256('upgrade_aquatic:river_planks')
stackTo256('upgrade_aquatic:river_pressure_plate')
stackTo256('upgrade_aquatic:river_sign')
stackTo256('upgrade_aquatic:river_slab')
stackTo256('upgrade_aquatic:river_stairs')
stackTo256('upgrade_aquatic:river_trapdoor')
stackTo256('upgrade_aquatic:river_wood')
stackTo256('upgrade_aquatic:rock_coral_block')
stackTo256('upgrade_aquatic:silk_coral_block')
stackTo256('upgrade_aquatic:star_coral_block')
stackTo256('upgrade_aquatic:stripped_driftwood')
stackTo256('upgrade_aquatic:stripped_driftwood_log')
stackTo256('upgrade_aquatic:stripped_river_log')
stackTo256('upgrade_aquatic:stripped_river_wood')
stackTo256('upgrade_aquatic:thrasher_spawn_egg' )
stackTo256('upgrade_aquatic:white_searocket')
stackTo256('variantsandventures:gelid_spawn_egg' )
stackTo256('whiteenderman:white_enderman_spawn_egg' )
stackTo256('etcetera:iridescent_wool')
spawn_egg_farseer"
stackTo256('traddlite')
stackTo256('opper_pickaxe')
stackTo256('rafting_table')
stackTo256('iamond_sword')
stackTo256('rass_block')
stackTo256('bserver')