//priority: 1
ServerEvents.tags('painting_variant', event => {
    event.get('minecraft:placeable')
        .remove('alexsmobs:dog_poker')
        .remove('alexsmobs:nft')
        .remove('clayworks:baked')
        .remove('easel_does_it:layers')
        .remove('easel_does_it:monochrome')
        .remove('easel_does_it:portal')
        .remove('easel_does_it:vintage')
        .remove('ls_backport_paintings:backyard')
        .remove('ls_backport_paintings:humble')
        .remove('ls_backport_paintings:orb')
        .remove('ls_backport_paintings:sunflowers')
        .remove('supplementaries:bombs')
        .remove('upgrade_aquatic:coil')
        .remove('upgrade_aquatic:sightless')
        .remove('species:the_composition')
        .remove('autumnity:pumpkin')
        .remove('autumnity:snail')
})