//priority: 1
ServerEvents.tags('block', event => {
  event.add('gamma:concrete_powders', 'clayworks:concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:black_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:blue_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:brown_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:cyan_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:gray_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:green_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:light_blue_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:light_gray_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:lime_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:magenta_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:orange_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:pink_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:purple_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:red_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:white_concrete_powder')
  event.add('gamma:concrete_powders', 'minecraft:yellow_concrete_powder')
})

ServerEvents.tags('item', event => {
  event.add('gamma:ambient_discs', 'quark:music_disc_chatter')
  event.add('gamma:ambient_discs', 'quark:music_disc_crickets')
  event.add('gamma:ambient_discs', 'quark:music_disc_clock')
  event.add('gamma:ambient_discs', 'quark:music_disc_fire')
  event.add('gamma:ambient_discs', 'quark:music_disc_wind')
  event.add('gamma:ambient_discs', 'quark:music_disc_rain')
  event.add('gamma:ambient_discs', 'quark:music_disc_ocean')
  event.add('gamma:ambient_discs', 'quark:music_disc_drips')
})

ServerEvents.tags('item', event => {
  event.add('gamma:music_discs', 'minecraft:music_disc_13')
  event.add('gamma:music_discs', 'minecraft:music_disc_cat')
  event.add('gamma:music_discs', 'minecraft:music_disc_blocks')
  event.add('gamma:music_discs', 'minecraft:music_disc_chirp')
  event.add('gamma:music_discs', 'minecraft:music_disc_far')
  event.add('gamma:music_discs', 'minecraft:music_disc_mall')
  event.add('gamma:music_discs', 'minecraft:music_disc_mellohi')
  event.add('gamma:music_discs', 'minecraft:music_disc_stal')
  event.add('gamma:music_discs', 'minecraft:music_disc_strad')
  event.add('gamma:music_discs', 'minecraft:music_disc_ward')
  event.add('gamma:music_discs', 'minecraft:music_disc_11')
  event.add('gamma:music_discs', 'minecraft:music_disc_wait')
  event.add('gamma:music_discs', 'rediscovered:music_disc_calm4')
  event.add('gamma:music_discs', 'minecraft:music_disc_otherside')
  event.add('gamma:music_discs', 'minecraft:music_disc_5')
  event.add('gamma:music_discs', 'upgrade_aquatic:music_disc_atlantis')
  event.add('gamma:music_discs', 'minecraft:music_disc_pigstep')
  event.add('gamma:music_discs', 'minecraft:music_disc_relic')
  event.add('gamma:music_discs', 'alexsmobs:music_disc_thime')
  event.add('gamma:music_discs', 'kubejs:music_disc_dog')
  event.add('gamma:music_discs', 'kubejs:music_disc_eleven')
  event.add('gamma:music_discs', 'kubejs:music_disc_droopy2')
  event.add('gamma:music_discs', 'kubejs:music_disc_death')
  event.add('gamma:music_discs', 'kubejs:music_disc_acid')
  event.add('gamma:music_discs', 'kubejs:music_disc_reveal')
})

ServerEvents.tags('item', event => {
  event.add('alexsmobs:stradpole_growables', 'minecraft:gunpowder')
})

ServerEvents.tags('item', event => {
  event.add('quark:backpack_blocked', 'supplementaries:sack')
})

ServerEvents.tags('item', event => {
  event.removeAllTagsFrom('spawn:suspicious_stick')
})

ServerEvents.tags('item', event => {
  event.add('gamma:coral_blocks', 'upgrade_aquatic:acan_coral_block')
  event.add('gamma:coral_blocks', 'minecraft:brain_coral_block')
  event.add('gamma:coral_blocks', 'upgrade_aquatic:branch_coral_block')
  event.add('gamma:coral_blocks', 'minecraft:bubble_coral_block')
  event.add('gamma:coral_blocks', 'upgrade_aquatic:chrome_coral_block')
  event.add('gamma:coral_blocks', 'upgrade_aquatic:finger_coral_block')
  event.add('gamma:coral_blocks', 'minecraft:fire_coral_block')
  event.add('gamma:coral_blocks', 'minecraft:horn_coral_block')
  event.add('gamma:coral_blocks', 'upgrade_aquatic:moss_coral_block')
  event.add('gamma:coral_blocks', 'upgrade_aquatic:petal_coral_block')
  event.add('gamma:coral_blocks', 'upgrade_aquatic:pillow_coral_block')
  event.add('gamma:coral_blocks', 'upgrade_aquatic:rock_coral_block')
  event.add('gamma:coral_blocks', 'upgrade_aquatic:silk_coral_block')
  event.add('gamma:coral_blocks', 'upgrade_aquatic:star_coral_block')
  event.add('gamma:coral_blocks', 'minecraft:tube_coral_block')
})

ServerEvents.tags('item', event => {
  event.add('gamma:weird_food', 'minecraft:poisonous_potato')
  event.add('gamma:weird_food', 'quark:ancient_fruit')
})

ServerEvents.tags('item', event => {
  event.add('gamma:compost_ingredients', 'minecraft:glow_berries')
  event.add('gamma:compost_ingredients', 'ecologics:coconut_slice')
  event.add('gamma:compost_ingredients', 'minecraft:apple')
  event.add('gamma:compost_ingredients', 'minecraft:carrot')
  event.add('gamma:compost_ingredients', 'minecraft:potato')
  event.add('gamma:compost_ingredients', 'minecraft:beetroot')
  event.add('gamma:compost_ingredients', 'upgrade_aquatic:mulberry')
  event.add('gamma:compost_ingredients', 'minecraft:melon_slice')
  event.add('gamma:compost_ingredients', 'minecraft:kelp')
  event.add('gamma:compost_ingredients', 'minecraft:sweet_berries')
  event.add('gamma:compost_ingredients', 'galosphere:lichen_cordyceps')
  event.add('gamma:compost_ingredients', 'ecologics:prickly_pear')
  event.add('gamma:compost_ingredients', 'farmersdelight:pumpkin_slice')
  event.add('gamma:compost_ingredients', 'minecraft:fermented_spider_eye')
  event.add('gamma:compost_ingredients', 'minecraft:chorus_fruit')
})

ServerEvents.tags('item', event => {
  event.add('minecraft:creeper_drop_music_discs', 'minecraft:music_disc_pigstep')
})
