# Don't change this! Version used to track needed updates.
version = 0
biomeColorRain = false
biomeParticlesRadius = 32
mushroomSporeBiomes = [
    "minecraft:mushroom_fields"
]
mushroomSporeDensity = 10
fireflyBiomes = [
    "minecraft:swamp",
    "minecraft:mangrove_swamp",
    "minecraft:taiga",
    "minecraft:river",
    "wythers:autumnal_swamp",
    "wythers:ancient_mossy_swamp",
    "wythers:ancient_oak_swamp",
    "wythers:waterlily_swamp",
    "wythers:old_growth_taiga_swamp"
]
fireflyDensity = 2
pollenBiomes = [
    "minecraft:flower_forest",
    "minecraft:sunflower_plains"
]
pollenDensity = 50
sculkDustBiomes = [
    "minecraft:deep_dark"
]
sculkDustDensity = 5