// priority: 0

StartupEvents.registry('block', event => {

  const allcolors = ['white', 'orange', 'magenta', 'light_blue', 'yellow', 'lime', 'pink', 'gray', 'light_gray', 'cyan', 'purple', 'blue', 'brown', 'green', 'red', 'black']

  allcolors.forEach(color => {
    const prettyName = color.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')

    event.create(color + '_bricks')
      .displayName(prettyName + ' Bricks')
      .textureAll('gamma:block/bricks/' + color + '_bricks')
      .soundType('stone')
      .hardness(2)
      .resistance(6)
      .tagBlock('minecraft:mineable/pickaxe')
      .requiresTool(true)

    event.create(color + '_bricks_slab', 'slab')
      .displayName(prettyName + ' Brick Slab')
      .textureAll('gamma:block/bricks/' + color + '_bricks')
      .soundType('stone')
      .hardness(2)
      .resistance(6)
      .tagBlock('minecraft:mineable/pickaxe')
      .requiresTool(true)

    event.create(color + '_bricks_stairs', 'stairs')
      .displayName(prettyName + ' Brick Stairs')
      .textureAll('gamma:block/bricks/' + color + '_bricks')
      .soundType('stone')
      .hardness(2)
      .resistance(6)
      .tagBlock('minecraft:mineable/pickaxe')
      .requiresTool(true)

    event.create(color + '_bricks_wall', 'wall')
      .displayName(prettyName + ' Brick Wall')
      .textureAll('gamma:block/bricks/' + color + '_bricks')
      .soundType('stone')
      .hardness(2)
      .resistance(6)
      .tagBlock('minecraft:mineable/pickaxe')
      .requiresTool(true)
  })

  event.create('cement', 'falling')
    .displayName('Cement')
    .textureAll('gamma:block/cement')
    .soundType('sand')
    .hardness(4)
    .resistance(3)
    .tagBlock('minecraft:mineable/shovel')
    .tagBlock('minecraft:sand')
    .requiresTool(true)

  event.create('moonstone')
    .displayName('§bMoonstone')
    .textureAll('gamma:block/moonstone')
    .soundType('lodestone')
    .hardness(4)
    .resistance(3)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')
    .requiresTool(true)

  event.create('bismuth_block')
    .displayName('Block of Bismuth')
    .textureAll('gamma:block/bismuth_block')
    .soundType('metal')
    .hardness(3)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('suspicious_block')
    .displayName('§bSuspicious Block')
    .textureAll('gamma:block/debug2')
    .soundType('amethyst')
    .hardness(3)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('lava_lamp')
    .displayName('Lava Lamp')
    .textureAll('gamma:block/lava_lamp')
    .soundType('lantern')
    .hardness(2)
    .resistance(2)
    .lightLevel(1.0)

  event.create('mysterious_cobblestone')
    .displayName('§dMysterious Mossy Cobblestone')
    .textureAll('gamma:block/mysterious_cobblestone')
    .soundType('stone')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('gloomy_tiles')
    .displayName('§eGloomy Tiles')
    .textureAll('gamma:block/gloomy_tiles')
    .soundType('nether_bricks')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('gloomy_tiles_slab', 'slab')
    .displayName('§eGloomy Tiles Slab')
    .textureAll('gamma:block/gloomy_tiles')
    .soundType('nether_bricks')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('gloomy_tiles_stairs', 'stairs')
    .displayName('§eGloomy Tiles Stairs')
    .textureAll('gamma:block/gloomy_tiles')
    .soundType('nether_bricks')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('gloomy_tiles_wall', 'wall')
    .displayName('§eGloomy Tiles Wall')
    .textureAll('gamma:block/gloomy_tiles')
    .soundType('nether_bricks')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('rock_salt')
    .displayName('Rock Salt')
    .textureAll('gamma:block/rock_salt')
    .soundType('basalt')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('mysterious_stone')
    .displayName('§dPlaceholderite')
    .model('gamma:block/mysterious_stone')
    .soundType('amethyst')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('silver_ore')
    .displayName('Silver Ore')
    .textureAll('gamma:block/silver_ore')
    .soundType('stone')
    .hardness(3)
    .resistance(3)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:ores/silver')
    .tagBlock('forge:ores')
    .requiresTool(true)

  event.create('raw_silver_block')
    .displayName('Block of Raw Silver')
    .textureAll('gamma:block/raw_silver_block')
    .soundType('stone')
    .hardness(5)
    .resistance(6)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks/raw_silver')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

})