// priority: 0

StartupEvents.registry('block', event => {

  event.create('smooth_stone_bricks')
    .displayName('Smooth Stone Bricks')
    .textureAll('gamma:block/smooth_stone_bricks')
    .soundType('stone')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('polished_rock_salt')
    .displayName('Polished Rock Salt')
    .textureAll('gamma:block/polished_rock_salt')
    .soundType('basalt')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('lava_lamp')
    .displayName('Lava Lamp')
    .textureAll('gamma:block/lava_lamp')
    .soundType('lantern')
    .hardness(2)
    .resistance(2)
    .lightLevel(1.0)

  event.create('gloomy_tiles')
    .displayName('Gloomy Tiles')
    .textureAll('gamma:block/gloomy_tiles')
    .soundType('nether_bricks')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('gloomy_tiles_slab', 'slab')
    .displayName('Gloomy Tiles Slab')
    .textureAll('gamma:block/gloomy_tiles')
    .soundType('nether_bricks')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('gloomy_tiles_stairs', 'stairs')
    .displayName('Gloomy Tiles Stairs')
    .textureAll('gamma:block/gloomy_tiles')
    .soundType('nether_bricks')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('gloomy_tiles_wall', 'wall')
    .displayName('Gloomy Tiles Wall')
    .textureAll('gamma:block/gloomy_tiles')
    .soundType('nether_bricks')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('rock_salt')
    .displayName('Rock Salt')
    .textureAll('gamma:block/rock_salt')
    .soundType('basalt')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('ruby_tiles')
    .displayName('Ruby Tiles')
    .textureAll('gamma:block/ruby_tiles')
    .soundType('amethyst')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true)

  event.create('silver_ore')
    .displayName('Silver Ore')
    .textureAll('gamma:block/silver_ore')
    .soundType('stone')
    .hardness(3)
    .resistance(3)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:ores/silver')
    .tagBlock('forge:ores')
    .requiresTool(true)

  event.create('raw_silver_block')
    .displayName('Block of Raw Silver')
    .textureAll('gamma:block/raw_silver_block')
    .soundType('stone')
    .hardness(5)
    .resistance(6)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks/raw_silver')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

})