StartupEvents.registry('painting_variant', event => {
    
//Kristoffer Zetterstrand Paintings:
    event.create('gamma:apples').width(32).height(32).tag('minecraft:placeable')
    event.create('gamma:backyard').width(48).height(64).tag('minecraft:placeable')
    event.create('gamma:bouquet').width(48).height(48).tag('minecraft:placeable')
    event.create('gamma:cavebird').width(48).height(48).tag('minecraft:placeable')
    event.create('gamma:changing').width(64).height(32).tag('minecraft:placeable')
    event.create('gamma:cotan').width(48).height(48).tag('minecraft:placeable')
    event.create('gamma:dante').width(64).height(64).tag('minecraft:placeable')
    event.create('gamma:dresses').width(16).height(16).tag('minecraft:placeable')
    event.create('gamma:endboss').width(48).height(48).tag('minecraft:placeable')
    event.create('gamma:fern').width(48).height(48).tag('minecraft:placeable')
    event.create('gamma:finding').width(64).height(32).tag('minecraft:placeable')
    event.create('gamma:forget_me_not').width(16).height(16).tag('minecraft:placeable')
    event.create('gamma:geology').width(32).height(32).tag('minecraft:placeable')
    event.create('gamma:ledge').width(32).height(64).tag('minecraft:placeable')
    event.create('gamma:lion').width(48).height(48).tag('minecraft:placeable')
    event.create('gamma:lowmist').width(64).height(32).tag('minecraft:placeable')
    event.create('gamma:meditative').width(16).height(16).tag('minecraft:placeable')
    event.create('gamma:monologue').width(16).height(16).tag('minecraft:placeable')
    event.create('gamma:opening').width(32).height(32).tag('minecraft:placeable')
    event.create('gamma:owlemons').width(48).height(48).tag('minecraft:placeable')
    event.create('gamma:passage').width(64).height(32).tag('minecraft:placeable')
    event.create('gamma:pergola').width(32).height(32).tag('minecraft:placeable')
    event.create('gamma:pond').width(48).height(64).tag('minecraft:placeable')
    event.create('gamma:therest').width(16).height(16).tag('minecraft:placeable')
    event.create('gamma:tides').width(48).height(48).tag('minecraft:placeable')
    event.create('gamma:winter_ruins').width(16).height(16).tag('minecraft:placeable')
})
