StartupEvents.registry('sound_event', (event) => {
	event.create('gamma:music.skylands')
	event.create('gamma:music.nether')
	event.create('gamma:music_disc.dog')
	event.create('gamma:music_disc.eleven')
	event.create('gamma:music_disc.droopy2')
	event.create('gamma:music_disc.death')
	event.create('gamma:music_disc.acid')
	event.create('gamma:music.menu')
	event.create('gamma:suspicious.breath')
})