! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null
galosphere:crystal_canyons > null
galosphere:pink_salt_caves > null
hybrid_beta:autumnal_forest > null
hybrid_beta:rainforest > null
hybrid_beta:seasonal_forest > null
hybrid_beta:temperate_rainforest > null
minecraft:crimson_forest > null
minecraft:dripstone_caves > null
minecraft:mangrove_swamp > wythers:autumnal_forest
minecraft:warped_forest > null
wythers:ancient_copper_beech_forest > null
wythers:ancient_emerald_beech_forest > minecraft:dark_forest
wythers:ancient_golden_beech_forest > null
wythers:ancient_moss_forest > null
wythers:ancient_mossy_swamp > null
wythers:ancient_oak_swamp > null
wythers:autumnal_swamp > wythers:autumnal_forest
wythers:bayou > wythers:autumnal_forest
wythers:birch_swamp > wythers:autumnal_forest
wythers:black_beach > null
wythers:black_river > null
wythers:crimson_tundra > null
wythers:fen > null
wythers:forbidden_forest > minecraft:dark_forest
wythers:fungous_dripstone_caves > null
wythers:gravelly_beach > null
wythers:gravelly_river > null
wythers:harvest_fields > null
wythers:jungle_river > null
wythers:lantern_river > null
wythers:lichenous_dripstone_caves > null
wythers:lush_dripstone_caves > null
wythers:lush_fungous_dripstone_caves > null
wythers:mossy_dripstone_caves > null
wythers:phantasmal_forest > null
wythers:phantasmal_swamp > null
wythers:salt_lakes_pink > null
wythers:salt_lakes_turquoise > null
wythers:salt_lakes_white > null
wythers:snowy_fen > null
wythers:tropical_beach > null
wythers:tropical_volcano > null
wythers:volcanic_chamber > null
wythers:volcanic_crater > null
wythers:volcano > null
wythers:waterlily_swamp > null
wythers:wistman_woods > null